# Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /source
COPY . .
RUN dotnet restore "./Pizzashop.csproj" --disable-parallel
RUN dotnet publish "./Pizzashop.csproj" -c release -o /app --no-restore

# Serve
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
ARG BUILD_CONFIGURATION=Release
WORKDIR /app
COPY --from=build /app ./

EXPOSE 5000
EXPOSE 5001

ENTRYPOINT ["dotnet", "Pizzashop.dll" ]